### ISSUE TITLE
Some ideas and suggestions

### ISSUE THREAD

**Issue by smikis** [avivbiton/BlizzardApiReader#16]
Hi, I wrote some new api calls for diablo api, and here are some things I noticed:
1. We should write interfaces instead of concrete types. It will help with unit tests immensely in the future, and some projects are using DI, so they'd need to create interfaces themselves in this case...
2. Maybe this should be Nuget package? It would be much more easier to use than compiling dll's and adding them to project
3. This is debatable, but I think it'd better to support .Net Core, especially if you're thinking about longevity
4. You could use RestSharp for api calls

**Comment by smikis** [comment]
Regarding interfaces, in my opinion all of the dependencies should have interface, so you can mock them easily in tests. But it wouldn't hurt to have client interfaces as well, in case you'd want to inject them. Not sure if I'm explaining it well, so if I'll have time I'll create pull request this evening to show how I imagine it

**Comment by avivbiton** [comment]
Yeah, it does make sense to me, I will wait and see how you'd implement it.
