### ISSUE TITLE
Separate project for each game API

### ISSUE THREAD

**Issue by linahanner** [avivbiton/BlizzardApiReader#18]
For the use case where a developer wants the reader for the World of Warcraft API but not the Diablo API the project will contain an unnecessary amount of models and implementations. I suggest separating the Readers and Models of the various Game APIs into multiple projects, one for each game all contained within the solution.

That is to say the BlizzardApiReader solution would look as follows (as an example):
- BlizzardApiReader.Core (interface of the api reader, and other generic classes)
- BlizzardApiReader.Diablo (with Diablo models and implementation of api reader)
- BlizzardApiReader.WorldOfWarcraft (with WorldOfWarcraft models and implementation of api reader)

This way the projects can be compiled into separate packages which are modular and contains no more than is relevant for the use case of that specific package, yet at the same time granting the ability to reference all of the packages in the event that a developer wants the ApiReader for multiple Game APIs.

I can implement this over the weekend, @avivbiton. What do you think?

**Comment by avivbiton** [comment]
I've seen your changes you made to your forked repo and I really like them and would like to push them forwards. Gj

**Comment by linahanner** [comment]
@avivbiton
Pull request: #19

Have a look whenever possible, it includes refactoring of quite a few parts, as written in the description of the pull request.

**Comment by avivbiton** [comment]
merged!
