### ISSUE TITLE
Migrate to .NET Core

### ISSUE THREAD

**Issue by linahanner** [avivbiton/BlizzardApiReader#20]
As mentioned by @smikis in #16 - building the library in .NET Core would increase the longevity of the APIReader since .NET Core is the standard of ASP.NET which is more commonly being used for new development. Have created a separate issue for this to be able to better track the progress, and discussions of the migration.

Relevant resource:
[Migrate from ASP.NET to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-2.1)

**Comment by avivbiton** [comment]
This is now a .net core project
