### ISSUE TITLE
Implement GetDefaultLocale

### ISSUE THREAD

**Issue by linahanner** [avivbiton/BlizzardApiReader#21]
Method GetDefaultLocale of class ApiConfiguration returns a hard-coded value regardless of the Region argument - implement method to return the right Locale for the right Region.

From testing towards Blizzard's API the default Locales for each Region appears to be:
- Europe (EU) = British English (en_GB)
- United States (US) = American English (en_US)
- Korea (KR) = Korean (ko_KR)
- Taiwan (TW) = Traditional Chinese (zh_TW)
- Southeast Asia (SEA) = American English (en_US)

**Comment by linahanner** [comment]
Yes, that's right. Instead of implementing it as a method of ApiConfiguration it has been created as an Extension method of the Region enum.

**Comment by avivbiton** [comment]
@linahanner please take a look at the enumExtension.cs file. Porting to .net core removed the line that forced the generic to be an enum.  
https://github.com/avivbiton/BlizzardApiReader/blob/master/BlizzardApiReader.Core/Extensions/EnumExtensions.cs  
(On mobile. Sorry for formating)

**Comment by linahanner** [comment]
I'll have a look asap @avivbiton

**Comment by linahanner** [comment]
Check out the most recent pull request (#27)

The ability to specify the GenericType to an Enum requires an upgraded version of the C# language (7.3)

**Comment by avivbiton** [comment]
Thanks wasn't exactly sure if this feature is available in core
