### ISSUE TITLE
HttpClient vs WebClient

### ISSUE THREAD

**Issue by redmars27** [avivbiton/BlizzardApiReader#42]
I am learning here so I am curious to understand why you used WebClient instead of HttpClient. If you are using Dot Net Core, shouldn't be better to use HttpClient. Let me know if I can help in any way.

**Comment by avivbiton** [comment]
IWebClient is an interface I made to wrap the HttpClient to make it more testable, it basically uses the HttpClient from .net core  
The implementation is very simple, you can see it here: https://github.com/avivbiton/BlizzardApiReader/blob/master/BlizzardApiReader.Core/Models/ApiWebClient.cs  
  
Tell me if you have any further questions.

**Comment by redmars27** [comment]
My bad, I didn't see the "i", please, close this issue as incorrect. The only other thing to recommend, please, read this: [https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) as it might have issues if the library is used heavily. Or use dependency injection.

**Comment by avivbiton** [comment]
Thank you, I will update the IWebClient to use shared instance of HttpClient.
